CREATE TABLE DISCUSSION_COMMENT ( -- 찬반 댓글 저장 테이블
    COMMENT_ID         NUMBER PRIMARY KEY,         -- 댓글 고유번호
    DISCUSSION_ID      NUMBER NOT NULL,            -- 어느 토론글에 달린 댓글인지 (외래키)
    USER_ID            VARCHAR2(50) NOT NULL,      -- 댓글 작성자 ID
    OPINION_TYPE       CHAR(1) CHECK(OPINION_TYPE IN ('T', 'F')) NOT NULL, -- 찬성/반대
    CONTENT            CLOB NOT NULL,              -- 댓글 내용
    CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP,  -- 작성 시간
    CONSTRAINT FK_DISCUSSION FOREIGN KEY (DISCUSSION_ID)
        REFERENCES DISCUSSION_POST(DISCUSSION_ID) ON DELETE CASCADE
);

CREATE SEQUENCE COMMENT_SEQ START WITH 1 INCREMENT BY 1;

-- 댓글 자동번호 트리거
CREATE OR REPLACE TRIGGER DISCUSSION_COMMENT_TRG
BEFORE INSERT ON DISCUSSION_COMMENT
FOR EACH ROW
BEGIN
    SELECT COMMENT_SEQ.NEXTVAL INTO :NEW.COMMENT_ID FROM DUAL;
END;

COMMENT ON TABLE DISCUSSION_COMMENT IS '찬반 댓글 저장';
COMMENT ON COLUMN DISCUSSION_COMMENT.COMMENT_ID IS '댓글 고유번호';
COMMENT ON COLUMN DISCUSSION_COMMENT.DISCUSSION_ID  IS '토론글에 달린 댓글 (외래키)';
COMMENT ON COLUMN DISCUSSION_COMMENT.USER_ID IS '댓글 작성자의 ID';
COMMENT ON COLUMN DISCUSSION_COMMENT.OPINION_TYPE IS '찬성/반대';
COMMENT ON COLUMN DISCUSSION_COMMENT.CONTENT IS '댓글의 내용';
COMMENT ON COLUMN DISCUSSION_COMMENT.CREATED_AT IS '작성한 시간';


